---
- hosts: apache
  sudo: yes 
  vars:
    domain: hello.com      
    domain_2: bye.com
    domain_3: good_morning.com
  tasks:
    - name: install apache2
      debug:
        msg: "Printing debug"       
    
